import Pagelayout from '/components/Pagelayout';
import { useGetBlogsPages } from 'actions/pagination';
import { getAllBlogs } from 'lib/api';
import { AiOutlineInstagram } from "react-icons/ai";
import { AiOutlineFacebook } from "react-icons/ai";
import Menuu from "../components/Menuu";
import Link from 'next/link'
export default function BlogsHome({blogs}) {

    const {
      pages,
      isLoadingMore,
      isReachingEnd,
      loadMore
    } = useGetBlogsPages({blogs});
  
  return (
    <>
    <Pagelayout>
    <div className="absolute bg-white top-4 w-screen  lg:right-10 text-center flex justify-center  z-10">
        <img
          src="/logo.png"
          alt="Picture of the author"
          className=" md:h-14 md:w-auto  h-10 w-32"
        />
         
      </div>
      <div className="absolute pl-2 pr-2 pb-2 pt-4 lg:px-4 lg:pb-4 lg:pt-6 flex w-screen justify-between ">
 <Link href='/'><a className="z-50"><img src="/logoo.png" className="md:ml-4 ml-2 md:w-8 w-8 h-auto  md:h-auto  drop-shadow-2xl brightness-150 saturate-200 "/></a></Link>
     <div className="z-40"></div> 
        <div className="flex  text-3xl mr-3  lg:text-5xl text-gray-200 ">
     
       <Menuu/>
       
        </div>
      </div>
    {/* <div className="absolute bg-black pb-4  overflow-x-hidden  lg:top-0  w-full flex justify-center z-10">
        <img
          src="/logo.png"
          alt="Picture of the author"
          className="relative top-2 w-40 h-12 "
        />
      </div>
      <div className="absolute overflow-x-hidden  px-2 lg:px-6  top-3 flex w-screen justify-between ">

        <Menu2 />
     
        <div className="flex text-3xl z-10  lg:text-5xl text-gray-200 ">
          {" "}
          <div className="hover:text-pink-800 hover:animate-ping">
          <AiOutlineInstagram />
          </div>
          <Link href="https://www.facebook.com/GreenestBuildings/">
          <a className="hover:text-blue-400 hover:animate-ping">
          <AiOutlineFacebook />
          </a>
          </Link>
        </div>
      </div> */}
    
      {/* {JSON.stringify(blogs)} */}
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
      <div className=" mt-12 relative lg:px-28 lg:py-20 py-14 mb-2   text-white grid grid-cols-1  md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-4 gap-5">
      {pages}
      <div className=" absolute text-center text-white  left-1/2 transform  -translate-x-1/2 bottom-0  bg-green-500  px-4 py-2  ">
    <button
      onClick={loadMore}
      disabled={isReachingEnd || isLoadingMore}
     >
      {isLoadingMore ? '...' : isReachingEnd ? 'No more blogs' : 'More Blogs'}
    </button>
  </div>
      </div>
     
    </Pagelayout>
  
</>
  )
}
// This function is called during the build (build time)
// Provides props to your page
// It will create static page
export async function getStaticProps() {
  const blogs = await getAllBlogs(({offset: 0}));
  return {
    props: {
      blogs
    }
  }
}

